spring.application.name=rabbit
spring.datasource.url=jdbc:postgresql://localhost:5432/rabbit
spring.datasource.username=myuser
spring.datasource.password=1234589
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
